### ISSUE TITLE
İT İS NOT A WORKT ON 1.14.3

### ISSUE THREAD

**Issue by successed** [biscuut/VoidChest#4]
i have ShopGUIPlus-1.19.7
can you update latest shopgui support ? 
[14:10:27 WARN]: [SellChest] Task #343 for SellChest v1.1.1 generated an exception
java.lang.NullPointerException: null
[14:10:27 WARN]: [SellChest] Task #344 for SellChest v1.1.1 generated an exception
java.lang.NullPointerException: null
at codes.biscuit.sellchest.utils.Utils.saveChestLocations(Utils.java:127) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by successed** [comment]
[11:00:06 WARN]: [SellChest] Task #341 for SellChest v1.1.1 generated an exception
java.lang.NullPointerException: null
        at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.14.3.jar:git-Paper-134]
        at codes.biscuit.sellchest.utils.Utils.lambda$runSellTimer$0(Utils.java:81) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-134]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by biscuut** [comment]
Try this version: https://send.firefox.com/download/dcdccb73556323c0/#BY9u8V3No27v9b54xxF_9w

**Comment by successed** [comment]
[09:14:08 WARN]: [SellChest] Task #328 for SellChest v1.1.2 generated an exception
java.lang.NullPointerException: null
        at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.14.4.jar:git-Paper-135]
        at codes.biscuit.sellchest.utils.Utils.lambda$runSellTimer$0(Utils.java:81) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-135]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by successed** [comment]
[latest.log](https://github.com/biscuut/SellChest/files/3415206/latest.log)
PLEASE FİX THİS PROBLEM!
